[package]
name = "rpade_triangular"
version = "0.1.0"
edition = "2024"

[dependencies]
matlab_base_wrapper = {path = "../matlab_base_wrapper"}
rpade_shared={ path = "../rpade_shared"}

[lib]
crate-type=["dylib"]
